apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-vpc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BigCat3997/gitops-rookie.git
    targetRevision: HEAD
    path: terraform-app/terraform-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
